### ISSUE TITLE
Handle ssurgo readonly error.

### ISSUE THREAD

**Issue by rogerlew** [rogerlew/wepppy#151]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wepppy/weppcloud/app.py", line 1927, in task_build_soil
    soils.build()
  File "/usr/lib/python3/dist-packages/wepppy/nodb/soils.py", line 352, in build
    self._build_gridded()
  File "/usr/lib/python3/dist-packages/wepppy/nodb/soils.py", line 606, in _build_gridded
    surgo_c = SurgoSoilCollection(mukeys)
  File "/usr/lib/python3/dist-packages/wepppy/soils/ssurgo/ssurgo.py", line 1135, in __init__
    n += self._sync('component', _fetch_components, 'mukey', mukeys)
  File "/usr/lib/python3/dist-packages/wepppy/soils/ssurgo/ssurgo.py", line 1281, in _sync
    cur.executemany(query, data)
sqlite3.OperationalError: attempt to write a readonly database

**Comment by mheilen** [comment]
Looks like this issue has resurfaced:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/wepppy/weppcloud/app.py", line 1927, in task_build_soil
soils.build()
File "/usr/lib/python3/dist-packages/wepppy/nodb/soils.py", line 352, in build
self._build_gridded()
File "/usr/lib/python3/dist-packages/wepppy/nodb/soils.py", line 606, in _build_gridded
surgo_c = SurgoSoilCollection(mukeys)
File "/usr/lib/python3/dist-packages/wepppy/soils/ssurgo/ssurgo.py", line 1135, in init
n += self._sync('component', _fetch_components, 'mukey', mukeys)
File "/usr/lib/python3/dist-packages/wepppy/soils/ssurgo/ssurgo.py", line 1281, in _sync
cur.executemany(query, data)
sqlite3.OperationalError: attempt to write a readonly database

**Comment by mheilen** [comment]
Is there a way to work around the ssurgo readonly error? Since build soils was working earlier, and now gets held up on this error, it seems like there must be a way to avoid the error.
