### ISSUE TITLE
Bug--not sure where

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#50]
I've ran the Blackwood watershed many times at once by only altering the CSA and MCL. This time I've only updated the codes (with pull) and added the wepp.set_hourly_seepage(True) command. The model got stuck in the third run (did finish two out of 15) and displayed the error below. I will rerun the code again as I see some "timeout" or "connection without response" errors but I am adding the error here in case you know where it is coming from. 

```
Traceback (most recent call last):
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/weppdev/PycharmProjects/wepppy/wepppy/scripts/watershed_Blackwood_test_csa_mcl.py", line 171, in <module>
    climate.build(verbose=1)
  File "/home/weppdev/PycharmProjects/wepppy/wepppy/nodb/climate.py", line 672, in build
    self._build_climate_multiple_observed()
  File "/home/weppdev/PycharmProjects/wepppy/wepppy/nodb/climate.py", line 993, in _build_climate_multiple_observed
    data = res.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/weppdev/PycharmProjects/wepppy/wepppy/climates/cligen_client.py", line 185, in observed_daymet
    r = requests.post(url, params=data)
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/requests/sessions.py", line 640, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/weppdev/PycharmProjects/wepppy/venv/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

Process finished with exit code 1
```

**Comment by rogerlew** [comment]
wepp is contacting cligen webservice on wepp1 to build climate for each hillslope. The bug occurs when the service times out. The Climate.MultipleObserved method will now attempt 10 tries before failing.
