### ISSUE TITLE
Climates not building

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#67]
I am trying to build wepp daymet climates for the Paradise Creek watershed here in Moscow and getting the error below. I've ran it fine last week, though.  

https://wepp1.nkn.uidaho.edu/weppcloud/runs/mdob0443-91e8-474d-a1c7-b434e068b803/0/

Error building climate

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wepppy/weppcloud/app.py", line 1544, in task_build_climate
    climate.build()
  File "/usr/lib/python3/dist-packages/wepppy/nodb/climate.py", line 636, in build
    self._build_climate_observed()
  File "/usr/lib/python3/dist-packages/wepppy/nodb/climate.py", line 758, in _build_climate_observed
    lng=ws_lng, lat=ws_lat
  File "/usr/lib/python3/dist-packages/wepppy/climates/cligen_client.py", line 199, in observed_daymet
    raise Exception("Encountered error retrieving from cligen")
Exception: Encountered error retrieving from cligen

**Comment by rogerlew** [comment]
daymet changed the formatting for how the files are returned. There is an extra line with metadata and the column headers changed:
year is now YEAR, yday is now DAY.

It fetches in my test script. Didn't have a change to check the interface, but it should work.?

**Comment by marianadobre** [comment]
Almost. Got this error:

Error building climate

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wepppy/weppcloud/app.py", line
1544, in task_build_climate
    climate.build()
  File "/usr/lib/python3/dist-packages/wepppy/nodb/climate.py", line
636, in build
    self._build_climate_observed()
  File "/usr/lib/python3/dist-packages/wepppy/nodb/climate.py", line
800, in _build_climate_observed
    data = res.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in
__get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/wepppy/climates/cligen_client.py",
line 199, in observed_daymet
    raise Exception("Encountered error retrieving from cligen")
Exception: Encountered error retrieving from cligen

**Comment by rogerlew** [comment]
Looks like the requests to daymet are failing occasionally. It is implemented so it will retry 10 times (for each hillslope) before giving up.

**Comment by marianadobre** [comment]
It's still not working. It gets stuck and won't move on. Doesn't give an
error, though.

**Comment by marianadobre** [comment]
Oh NO! They got some storms in their clouds. :)

Thanks for checking!

**Comment by rogerlew** [comment]
The daymet requests are sometimes working, but not reliably enough to build all the hillslopes. It looks like the header format reverted to what they had before. Within the last day they update the clients for their single pixel extraction tool to use a new url. I'd say we should avoid using the multiple hillslope for the next couple days and see if they get the bugs sorted out. All the additional requests probably aren't helping. 

The single climate might work, some of the time, except for when it doesn't. ;)

https://github.com/ornldaac/daymet-single-pixel-batch/commit/bb856da821f671cb49d0b9add68c0d55a56197d7#diff-dbcac071a6d45d89ee4345e21bbd069f

**Comment by marianadobre** [comment]
Sounds good, Roger! I can use the single climate with Prism adjustments for the class tomorrow.

Thanks for checking on this.
M

**Comment by rogerlew** [comment]
daymet observed has been reimplemented to use locally stored .nc4 files.
