### ISSUE TITLE
Error building channels

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#89]
Do you know what's the matter with this?

Building Channels Failed

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wepppy/weppcloud/app.py", line 1085, in task_build_channels
    topaz.build_channels(csa=csa, mcl=mcl)
  File "/usr/lib/python3/dist-packages/wepppy/nodb/topaz.py", line 196, in build_channels
    top_runner.build_channels()
  File "/usr/lib/python3/dist-packages/wepppy/topaz/topaz.py", line 912, in build_channels
    self._prep_dir()
  File "/usr/lib/python3/dist-packages/wepppy/topaz/topaz.py", line 202, in _prep_dir
    _cp_chmod(_join(topaz_bin, 'dednm'), _join(wd, 'dednm'), 0o755)
  File "/usr/lib/python3/dist-packages/wepppy/topaz/topaz.py", line 74, in _cp_chmod
    shutil.copyfile(src, dst)
  File "/usr/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 26] Text file busy: '/geodata/weppcloud_runs/mdob4714-d5ad-46db-a21c-02cc6e2b242b/dem/topaz/dednm'

**Comment by rogerlew** [comment]
Looks like it was trying to copy the dednm executable into your project folder. That is one of the TOPAZ programs. My guess is maybe the request to delineate the channels was accidently sent twice.

I should probably add a debounce so it ignores the second button push if it is pushed within a second or two of the first.

**Comment by marianadobre** [comment]
I see. Well, thanks for looking into it.
